Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.provision "shell", path: "provision/install_postgresql.sh"
  config.vm.provision "shell", path: "provision/install_flask.sh"
  config.vm.provision "shell", path: "provision/setup_app.sh"
end